### ISSUE TITLE
Uudelleenohjauksista puuttuu exit-komento

### ISSUE THREAD

**Issue by datahari** [Mariapori/tmForum#1]
Uudelleenohjauksista puuttuu exit-komento. Tämä mahdollistaa esim. lankojen lukemisen ilman kirjautumista:
```bash
curl http://fooruminosoite.com/langat.php
curl http://fooruminosoite.com/lanka.php?id=10
```
PHP:n header()-funktiolla tehdyn uudelleenohjauksen jälkeen tulisi aina kutsua exit; tai die(); jotta skriptin lataus keskeytetään.
```php
header( "Location: index.php" );
exit;
```

**Comment by Mariapori** [comment]
Totta muuten, tuo oli minun ensimmäisiä PHP-harjoitteluja joten hyvä vinkki.

Ensin ajattelin että voisi muutenkin sallia lankojen lukemisen mutta sitten aina on siirtynyt muiden juttujen takia.

Tuon toki voisin korjata.

Kiitokset!
