### ISSUE TITLE
Käyttäjien syöttämiä tekstejä ei ole XSS-suojattu

### ISSUE THREAD

**Issue by datahari** [Mariapori/tmForum#2]
Käyttäjien syötteistä, kuten lankojen nimistä ja viesteistä ei ole suodatettu HTML:ää. Tämä altistaa sovelluksen XSS-hyökkäykselle.

Syöttämällä langan otsikoksi seuraavan koodin, ylläpitäjän kirjautuessa sivuille kaikki langat poistetaan:
```html
<script>$(document).ready(function(){$(".lankalistassa a").each(function(){if($(this).html().indexOf("script") == 1) {return true;}PoistaLanka($(this).attr("href").replace(/[^0-9]+/g, ''))});});</script>
```

Asian voi korjata suodattamalla HTML kun tekstit tietokannasta tulostetaan:
```php
echo "<li><div class='lankalistassa'> <a href='lanka.php?id=".htmlspecialchars($row["LankaID"])."'>".htmlspecialchars($row["Nimi"])."</a><p>Luonut: ".htmlspecialchars($row["Kayttajanimi"])." | ".date_format($date,'d.m.Y')."";
```

**Comment by Mariapori** [comment]
Kyllä, kirjautumiskentissä olen käyttänyt mysql_escape_string mutta en ole varmaan muistanut joka paikasta noita suodattaa. 

Tämä on ollut sellainen nopea testi vaan ja ensimmäinen PHP-projekti joten voi varmasti olla vielä muitakin mahdollisia reikiä.

Kiitos!

**Comment by datahari** [comment]
Tuota mysql_escape_string-funktiota käytetään sql-kyselyjen suodattamiseen (suosittelisin mieluummin käyttämään prepared statementsejä tosin), mutta tässä on kyse siitä, kun printataan ulos tietokannassa oleva tieto. Siihen tuo mysql_escape_string ei vaikuta mitenkään.

Ajattelinkin, että on varmaan vain testailua ja harjoittelua, mutta päätin ilmoittaa vioista jos vaikka jossain on varsinaisessa käytössäkin tämä, tai jos jossain muussa projektissa on sama virhe. Parempi oppia virheistä jo harjoitusprojekteissa 😃

**Comment by Mariapori** [comment]
Se on juurikin näin, nämä ovat kullanarvoisia vinkkejä! 

Ja joo tosiaan nuo sql injektiot olen pyrkinyt tuolla välttämään, tuota html escapea en ole varmaan edes tuossa harjoituksessa tainnut ajatella, mutta joo ei se ole missään muodossa järkevää että käyttäjä pystyisi itse läpsimään javascriptiä ja html sovelluksessa. 😅
